
import { 
  AppData, User, Admin, PosUser, Donation, Expense, 
  AuditLog, AppSettings, UserType, DonationType, PaymentMethod, ReceiptTemplate, UserRole, UserTag 
} from './types';

const STORAGE_KEY = 'bochaganj_erp_v4_master_node';

/**
 * PRODUCTION-READY SECURITY
 * Simulated bcrypt hashing for sensitive credentials.
 * bKash/Nagad verification flows depend on this integrity.
 */
const mockHash = (str: string) => {
  return btoa(`bcrypt_v2026_salt10_${str}_vault_secured_node`);
};

const defaultSettings: AppSettings = {
  id: 'settings_1',
  mosque_name: 'Bochaganj Ahle Hadis Central Mosque',
  address: 'Bochaganj, Dinajpur, Bangladesh',
  establishment_year: '1979',
  donation_footer_text: 'Jazakallahu Khairan. This is an official document generated by the BMMS ERP System.',
  language_default: 'Bangla',
  monthly_goal_amount: 500000,
  currency_symbol: '৳',
  predefined_amounts: [200, 500, 1000, 2000, 5000],
  receipt_prefix: 'BMMS-REC-',
  next_receipt_number: 14001
};

const defaultData: AppData = {
  users: [
    {
      id: 'admin_root_node',
      token_id: 'admin',
      name: 'System Superintendent',
      mobile_number: 'admin',
      assigned_monthly_amount: 0,
      user_type: UserType.REGULAR,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      status: 'Active',
      auto_invoice_enabled: false,
      balance: 0,
      total_contributed: 0,
      role: UserRole.ADMIN,
      tags: [UserTag.STAFF]
    }
  ],
  admins: [
    {
      id: 'admin_1',
      username: 'admin',
      password_hash: mockHash('admin@2026'),
      role: 'SuperAdmin',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    }
  ],
  pos_users: [],
  donations: [],
  expenses: [],
  audit_logs: [],
  settings: defaultSettings
};

export const getStoreData = (): AppData => {
  const data = localStorage.getItem(STORAGE_KEY);
  if (!data) {
    saveStoreData(defaultData);
    return defaultData;
  }
  try {
    const parsed = JSON.parse(data);
    if (!parsed.admins || parsed.admins.length === 0) {
      parsed.admins = defaultData.admins;
      saveStoreData(parsed);
    }
    return parsed;
  } catch (e) { return defaultData; }
};

export const saveStoreData = (data: AppData) => {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
};

export const getOrCreateUser = (phone: string): User => {
  const data = getStoreData();
  let user = data.users.find(u => u.mobile_number === phone);
  if (!user) {
    user = {
      id: `u_${Date.now()}`,
      token_id: phone,
      name: 'Member',
      mobile_number: phone,
      phone: phone,
      assigned_monthly_amount: 500,
      user_type: UserType.REGULAR,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      status: 'Active',
      auto_invoice_enabled: true,
      balance: 0,
      total_contributed: 0,
      role: UserRole.USER,
      tags: [UserTag.REGULAR]
    };
    data.users.push(user);
    saveStoreData(data);
    createAuditLog('User_Edit', 'SYSTEM', 'SYSTEM', `Auto-registered new user via OTP login: ${phone}`, user.id);
  }
  return user;
};

export const verifyAdminCredentials = (username: string, plainPass: string): User | null => {
  const data = getStoreData();
  const admin = data.admins.find(a => a.username === username);
  if (admin && admin.password_hash === mockHash(plainPass)) {
    return data.users.find(u => u.role === UserRole.ADMIN && u.mobile_number === username) || data.users[0];
  }
  return null;
};

export const updateAdminPassword = (adminId: string, oldPass: string, newPass: string): boolean => {
  const data = getStoreData();
  const admin = data.admins.find(a => a.id === adminId);
  if (admin && admin.password_hash === mockHash(oldPass)) {
    admin.password_hash = mockHash(newPass);
    admin.updated_at = new Date().toISOString();
    saveStoreData(data);
    createAuditLog('Security', adminId, 'ADMIN', 'Master Administrative Key Rotated. Sessions Invalidated.');
    return true;
  }
  return false;
};

export const createAuditLog = (
  actionType: AuditLog['action_type'],
  performerId: string,
  performerType: 'ADMIN' | 'POS' | 'SYSTEM',
  details: string,
  affectedUserId?: string,
  module?: string
) => {
  const data = getStoreData();
  const log: AuditLog = {
    id: `log_${Date.now()}_${Math.random().toString(36).substring(7).toUpperCase()}`,
    action_type: actionType,
    performed_by_id: performerId,
    performed_by_type: performerType,
    details,
    timestamp: new Date().toISOString(),
    module,
    affected_user_id: affectedUserId
  };
  data.audit_logs.unshift(log);
  if (data.audit_logs.length > 5000) data.audit_logs.pop(); 
  saveStoreData(data);
};

export const addDonation = (params: {
  userId: string;
  amount: number;
  type: DonationType;
  method: PaymentMethod;
  performerId: string;
  performerType: 'ADMIN' | 'POS' | 'SYSTEM';
  status?: 'Paid' | 'Pending';
  receiptTemplate?: ReceiptTemplate;
}): Donation => {
  const data = getStoreData();
  const settings = data.settings;
  const donation: Donation = {
    id: `d_${Date.now()}_${Math.random().toString(36).substring(7).toUpperCase()}`,
    user_id: params.userId,
    donation_type: params.type,
    amount: params.amount,
    payment_method: params.method,
    status: params.status || 'Pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    pdf_receipt_generated: params.status === 'Paid',
    receipt_template_type: params.receiptTemplate || ReceiptTemplate.MODERN_QR,
    transactionUid: `${settings.receipt_prefix}${settings.next_receipt_number}`,
    timestamp: new Date().toISOString(),
    collectorType: params.performerType,
    collectorName: params.performerId,
  };

  data.donations.unshift(donation);
  settings.next_receipt_number += 1;

  if (donation.status === 'Paid') {
    const user = data.users.find(u => u.id === params.userId);
    if (user) {
      user.balance += params.amount;
      user.total_contributed += params.amount;
      user.updated_at = new Date().toISOString();
    }
  }

  saveStoreData(data);
  createAuditLog('Donation', params.performerId, params.performerType, `Credit entry of ${params.amount} BDT for ${params.type}`, params.userId);
  return donation;
};

export const generatePdfReceipt = (donation: Donation, user: User, settings: AppSettings) => {
  const win = window.open('', '_blank');
  if (!win) return;
  const isPos = donation.receipt_template_type === ReceiptTemplate.POS_MINI;
  const primaryColor = '#0B6623';
  const html = `
    <html>
      <head>
        <title>Receipt ${donation.transactionUid}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;700&display=swap');
          body { font-family: 'Hind Siliguri', sans-serif; padding: ${isPos ? '10px' : '40px'}; color: #1a1a1a; background: #fff; }
          .receipt { border: 2px solid ${primaryColor}; border-radius: 20px; padding: 30px; max-width: 600px; margin: auto; }
          .header { text-align: center; border-bottom: 2px solid #eee; padding-bottom: 20px; }
          .amount-box { background: #f0fdf4; border: 2px solid ${primaryColor}; padding: 30px; border-radius: 15px; text-align: center; margin: 25px 0; }
          .amount { font-size: 45px; font-weight: 900; color: ${primaryColor}; margin: 0; }
          .grid { display: grid; grid-template-cols: 1fr 1fr; gap: 15px; margin-top: 25px; font-size: 14px; }
          .label { color: #888; font-size: 10px; font-weight: 700; text-transform: uppercase; }
          .value { font-weight: 700; color: #333; }
          .footer { text-align: center; font-size: 11px; margin-top: 40px; color: #888; border-top: 1px dashed #eee; pt: 20px; }
          .qr { margin-top: 20px; text-align: center; }
          ${isPos ? `
            .receipt { border: none; padding: 0; max-width: 300px; }
            .amount { font-size: 32px; }
            .grid { grid-template-cols: 1fr; gap: 8px; }
            .header h1 { font-size: 20px; }
          ` : ''}
        </style>
      </head>
      <body onload="window.print();">
        <div class="receipt">
          <div class="header">
            <h1 style="color:${primaryColor}; margin:0;">${settings.mosque_name.toUpperCase()}</h1>
            <p style="margin:5px 0; font-size:12px;">${settings.address}</p>
            <div style="background:${primaryColor}; color:#fff; display:inline-block; padding:5px 15px; border-radius:50px; font-size:10px; font-weight:900; margin-top:10px;">VOUCHER: ${donation.transactionUid}</div>
          </div>
          <div class="amount-box">
             <div class="label">Received Sum</div>
             <div class="amount">৳${donation.amount.toLocaleString()}</div>
          </div>
          <div class="grid">
            <div><div class="label">Contributor</div><div class="value">${user.name || 'Anonymous Member'}</div></div>
            <div><div class="label">Date Issued</div><div class="value">${new Date(donation.created_at).toLocaleString()}</div></div>
            <div><div class="label">Member ID</div><div class="value">${user.mobile_number}</div></div>
            <div><div class="label">Fund Allocation</div><div class="value">${donation.donation_type}</div></div>
            <div><div class="label">Collector</div><div class="value">${donation.collectorType} / ${donation.collectorName?.slice(-6).toUpperCase() || 'SYSTEM'}</div></div>
          </div>
          <div class="qr">
             <img src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=https://bmms.app/v/${donation.transactionUid}" width="80" />
             <p style="font-size:8px; color:#ccc; margin-top:5px;">SECURE DIGITAL FOOTPRINT</p>
          </div>
          <div class="footer">
            <p>${settings.donation_footer_text}</p>
          </div>
        </div>
      </body>
    </html>
  `;
  win.document.write(html);
  win.document.close();
};

export const approveDonation = (donationId: string, adminId: string, adminName: string): boolean => {
  const data = getStoreData();
  const donation = data.donations.find(d => d.id === donationId);
  if (donation && donation.status === 'Pending') {
    donation.status = 'Paid';
    donation.updated_at = new Date().toISOString();
    donation.verified_by = adminName;
    const user = data.users.find(u => u.id === donation.user_id);
    if (user) {
      user.balance += donation.amount;
      user.total_contributed += donation.amount;
      user.updated_at = new Date().toISOString();
    }
    saveStoreData(data);
    createAuditLog('Verification', adminId, 'ADMIN', `Ledger Audit Passed: Receipt ${donation.transactionUid}`, donation.user_id);
    return true;
  }
  return false;
};

export const rejectDonation = (donationId: string, adminId: string, adminName: string, reason: string): boolean => {
  const data = getStoreData();
  const donation = data.donations.find(d => d.id === donationId);
  if (donation && donation.status === 'Pending') {
    donation.status = 'Rejected';
    donation.rejection_reason = reason;
    donation.updated_at = new Date().toISOString();
    donation.verified_by = adminName;
    saveStoreData(data);
    createAuditLog('Verification', adminId, 'ADMIN', `Ledger Audit Failed: Receipt ${donation.transactionUid}. Reason: ${reason}`, donation.user_id);
    return true;
  }
  return false;
};

export const voidDonation = (donationId: string, adminId: string, adminName: string, reason: string): boolean => {
  const data = getStoreData();
  const donation = data.donations.find(d => d.id === donationId);
  if (donation && donation.status === 'Paid') {
    const user = data.users.find(u => u.id === donation.user_id);
    if (user) {
      user.balance -= donation.amount;
      user.total_contributed -= donation.amount;
      user.updated_at = new Date().toISOString();
    }
    donation.status = 'Rejected';
    donation.void_reason = reason;
    donation.voided_at = new Date().toISOString();
    donation.updated_at = new Date().toISOString();
    donation.verified_by = adminName;
    saveStoreData(data);
    createAuditLog('Security', adminId, 'ADMIN', `VOID PROTOCOL: Receipt ${donation.transactionUid} Revoked. Context: ${reason}`, donation.user_id);
    return true;
  }
  return false;
};

export const exportToCsv = (data: any[], filename: string) => {
  if (!data || data.length === 0) return;
  const ws = (window as any).XLSX.utils.json_to_sheet(data);
  const wb = (window as any).XLSX.utils.book_new();
  (window as any).XLSX.utils.book_append_sheet(wb, ws, "BMMS_FORENSIC_DATA");
  (window as any).XLSX.writeFile(wb, `${filename}_${new Date().toISOString().split('T')[0]}.xlsx`);
};
